name: Build container image

on:
  pull_request:

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build only
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: jenkins-plus:dev

      - name: Dockle
        uses: erzz/dockle-action@v1
        with:
          image: jenkins-plus:dev
          exit-code: '1'
          failure-threshold: fatal

      - name: Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: jenkins-plus:dev
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
