name: Build container image

on:
  pull_request:

jobs:
  lint:
    name: Lint Dockerfile with hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
          verbose: true

  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build only
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          load: true
          push: false
          tags: jenkins-plus:dev

      - name: Dockle
        uses: erzz/dockle-action@v1
        with:
          image: jenkins-plus:dev
          exit-code: '1'
          failure-threshold: fatal

      - name: Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: jenkins-plus:dev
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
